version: '3.1'
services:
  db-lab:
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Sm@lD@t@P@swo4d
    volumes:
      - ./initial_scripts/:/docker-entrypoint-initdb.d